### ISSUE TITLE
[bug] throwHttpErrors can't be overridden

### ISSUE THREAD

**Issue by pocesar** [apifytech/http-request#32]
The spread on https://github.com/apifytech/http-request/blob/ad38f1d0f4834e6a647d90346a41e765b7eaccca/src/index.js#L100-L118 makes all the options below not being able to get overridden. 

which makes this part unreachable 
https://github.com/apifytech/http-request/blob/ad38f1d0f4834e6a647d90346a41e765b7eaccca/src/index.js#L148-L152

the current workaround is to check for the status code inside `abortFunction`. I was expecting my async function to throw on 40x/50x, lead to some really hard to debug situation. had to save the contents of the page to make sure that there was an error going on. 

EDIT: for some unknown reason, the "statusCode" property of the returned result is empty when the request fails as in:

```js
const response = await httpRequest(opts);
console.log(response.statusCode);
```

**Comment by metalwarrior665** [comment]
Hey Paulo,

Actually the JS spread should work correctly because the later property always wins.

Since you are dealing with Amazon, the issue might be how CheerioCrawler weirdly handles 500 statuses. In case of Amazon's 503, it doesn't return the proper status code but it throws and return some custom string error. This caught me off guard too so we may file an issue on apify-js repo too.  So in my checker actor I had to [parse the statusCode of this string error](https://github.com/metalwarrior665/actor-website-checker/blob/master/src/main.js#L126) :/

But maybe you mean something else here.

**Comment by pocesar** [comment]
you're right, I wrote this issue before the debugging part for the apify proxy url session limit, and I wasn't getting the `Request failed` error at all, and drilling down the many dependencies, because it's used internally by requestAsBrowser, the problem was elsewhere haha, thanks!
