### ISSUE TITLE
Issues with building iltorb with Apify SDK

### ISSUE THREAD

**Issue by jancurn** [apifytech/http-request#4]
Some users reported issued that they can't build `iltorb` dependency.

I'm thinking how we could improve this, maybe have it just as an optional dependency, and throw error only when people want to use the new request function?

**Comment by mnmkng** [comment]
I already talked about a similar thing with @petrpatek. I think that we should detect Node.js version in the new `http-request` package he's building and only include `iltorb` when Node.js is < 12 because Node.js 12 has native support for Brotli. This could eliminate some of the trouble as well.

Or we could enable brotli with a flag in the function, saying that you either need to have the `iltorb` optional dependency installed or Node.js > 12.

That's probably cleanest. And when we move to Node.js 12 in the future, we just remove the flag and include Brotli by default

**Comment by mnmkng** [comment]
I'm just thinking, when you do `npm install` locally, which is probably where users have trouble, because the platform works fine, it installs optional deps anyway, unless you run it with `--no-optional` which is annoying. So we'd probably have to leave it out of the `package.json` entirely...

**Comment by petrpatek** [comment]
@mnmkng I completely agree with the `useBrotli` flag. I did it this way. However, when writing this comment one more possibility comes to my mind.  We can let the user pass the function that decompresses the brotli. If the user runs the SDK on 12+ he can pass the native function and if he runs the 12- he can pass the function from the `ltorb`. It is not a best DX a suppose, but since it is only a temporary think it could work.

**Comment by jancurn** [comment]
And how about including `ltorb` as peer dependency only? See https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by jancurn** [comment]
BTW, we can surely make the Brotli encoding optional just for this package or ask user to pass the actual compression function, but that doesn't solve anything, because we need to use Brotli in the `requestAsBrowser` function all the time, otherwise, the function will provide different HTTP signature than Firefox, and it's completely useless.

But, if we include `ltorb` only as a peer dependency, it still needs to be installed manually. So, when user runs `requestAsBrowser` and Node version is lower than 12 and `ltorb` is not available, we throw an error with complete info how the user can fix this. I think this might work fine...

**Comment by mnmkng** [comment]
Yeah, that seems like a viable solution. Basically, `requestAsBrowser` would force `useBrotli: true`.

**Comment by petrpatek** [comment]
Fixed with using `iltorb` as a peer dependency.
